DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS category;
CREATE TABLE articles (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Title TEXT NOT NULL,
	SafeTitle TEXT NOT NULL,
	AuthorID TEXT NOT NULL,
	Date INTEGER NOT NULL,
	Category TEXT NOT NULL,
	Tags TEXT NOT NULL,
	CoverURL TEXT,
	CoverInfo TEXT,
	Pictures TEXT,
	Description TEXT NOT NULL,
	Content TEXT NOT NULL,
	Text TEXT NOT NULL
);
CREATE TABLE users (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Username TEXT NOT NULL,
	Picture TEXT,
	Password TEXT NOT NULL,
	Description TEXT
);
CREATE TABLE comments (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Date INTEGER NOT NULL,
	Email INTEGER NOT NULL,
	ArticleID INTEGER NOT NULL,
	Parent INTEGER NOT NULL,
	Level INTEGER NOT NULL,
	Comment TEXT NOT NULL
);
CREATE TABLE category (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Description TEXT NOT NULL,
	Color TEXT NOT NULL,
	Picture TEXT NOT NULL
);